/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedFortschrittRouteImport } from './routes/_authenticated/fortschritt'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedTagebuchRouteImport } from './routes/_authenticated/tagebuch'
import { Route as StravaCallbackRouteImport } from './routes/strava/callback'
import { Route as ApiShortcutsExerciseRouteImport } from './routes/api/shortcuts/exercise'
import { Route as ApiStravaWebhookRouteImport } from './routes/api/strava/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFortschrittRoute =
  AuthenticatedFortschrittRouteImport.update({
    id: '/fortschritt',
    path: '/fortschritt',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagebuchRoute = AuthenticatedTagebuchRouteImport.update({
  id: '/tagebuch',
  path: '/tagebuch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StravaCallbackRoute = StravaCallbackRouteImport.update({
  id: '/strava/callback',
  path: '/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShortcutsExerciseRoute = ApiShortcutsExerciseRouteImport.update({
  id: '/api/shortcuts/exercise',
  path: '/api/shortcuts/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaWebhookRoute = ApiStravaWebhookRouteImport.update({
  id: '/api/strava/webhook',
  path: '/api/strava/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fortschritt': typeof AuthenticatedFortschrittRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tagebuch': typeof AuthenticatedTagebuchRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/api/shortcuts/exercise': typeof ApiShortcutsExerciseRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fortschritt': typeof AuthenticatedFortschrittRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tagebuch': typeof AuthenticatedTagebuchRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/api/shortcuts/exercise': typeof ApiShortcutsExerciseRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/fortschritt': typeof AuthenticatedFortschrittRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/tagebuch': typeof AuthenticatedTagebuchRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/api/shortcuts/exercise': typeof ApiShortcutsExerciseRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fortschritt'
    | '/profil'
    | '/tagebuch'
    | '/strava/callback'
    | '/api/shortcuts/exercise'
    | '/api/strava/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fortschritt'
    | '/profil'
    | '/tagebuch'
    | '/strava/callback'
    | '/api/shortcuts/exercise'
    | '/api/strava/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/fortschritt'
    | '/_authenticated/profil'
    | '/_authenticated/tagebuch'
    | '/strava/callback'
    | '/api/shortcuts/exercise'
    | '/api/strava/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  StravaCallbackRoute: typeof StravaCallbackRoute
  ApiShortcutsExerciseRoute: typeof ApiShortcutsExerciseRoute
  ApiStravaWebhookRoute: typeof ApiStravaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fortschritt': {
      id: '/_authenticated/fortschritt'
      path: '/fortschritt'
      fullPath: '/fortschritt'
      preLoaderRoute: typeof AuthenticatedFortschrittRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tagebuch': {
      id: '/_authenticated/tagebuch'
      path: '/tagebuch'
      fullPath: '/tagebuch'
      preLoaderRoute: typeof AuthenticatedTagebuchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/strava/callback': {
      id: '/strava/callback'
      path: '/strava/callback'
      fullPath: '/strava/callback'
      preLoaderRoute: typeof StravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shortcuts/exercise': {
      id: '/api/shortcuts/exercise'
      path: '/api/shortcuts/exercise'
      fullPath: '/api/shortcuts/exercise'
      preLoaderRoute: typeof ApiShortcutsExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/webhook': {
      id: '/api/strava/webhook'
      path: '/api/strava/webhook'
      fullPath: '/api/strava/webhook'
      preLoaderRoute: typeof ApiStravaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFortschrittRoute: typeof AuthenticatedFortschrittRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedTagebuchRoute: typeof AuthenticatedTagebuchRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFortschrittRoute: AuthenticatedFortschrittRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedTagebuchRoute: AuthenticatedTagebuchRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  StravaCallbackRoute: StravaCallbackRoute,
  ApiShortcutsExerciseRoute: ApiShortcutsExerciseRoute,
  ApiStravaWebhookRoute: ApiStravaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
